sudo: false
language: node_js
node_js:
  - '8'

env:
  global:
    - CXX=g++-4.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
script:
  - npm test
  - npm run lint

after_success:
  - npm run test:coveralls
